import type { CSSProperties } from 'react';

// ─── Page styles ───
export const s: Record<string, CSSProperties> = {
  header: {
    height: 72, borderBottom: '1px solid var(--border-color)',
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '0 36px', background: 'var(--bg-secondary)', flexShrink: 0,
  },
  headerTitle: { fontSize: 20, fontWeight: 700, color: 'var(--text-primary)', margin: 0 },
  headerSub: { fontSize: 12, color: 'var(--text-muted)', margin: '2px 0 0' },
  main: {
    flex: 1, padding: '32px 36px', overflowY: 'auto',
    maxWidth: 860, width: '100%', margin: '0 auto',
  },
  stepRow: { display: 'flex', alignItems: 'center', marginBottom: 28 },
  stepItem: { display: 'flex', alignItems: 'center', gap: 10 },
  stepCircle: {
    width: 32, height: 32, borderRadius: '50%',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 13, fontWeight: 700, transition: 'all 0.3s',
  },
  stepLabel: { fontSize: 13, fontWeight: 600, transition: 'color 0.3s' },
  stepLine: { flex: 1, height: 2, margin: '0 16px', borderRadius: 2, transition: 'background 0.3s' },
  card: {
    background: 'var(--bg-secondary)', border: '1px solid var(--border-color)',
    borderRadius: 18, padding: '28px 32px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
  },
  cardSection: { marginBottom: 8 },
  sectionHead: { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 },
  sectionIcon: {
    width: 36, height: 36, borderRadius: 10,
    display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16,
  },
  sectionTitle: { fontSize: 15, fontWeight: 700, color: 'var(--text-primary)', margin: 0 },
  divider: { height: 1, background: 'var(--border-color)', margin: '24px 0' },
  fieldGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '16px 20px',
  },
  fieldWrap: { display: 'flex', flexDirection: 'column', gap: 6 },
  label: {
    fontSize: 11, fontWeight: 600, color: 'var(--text-secondary)',
    letterSpacing: 0.5, textTransform: 'uppercase',
  },
  input: {
    padding: '11px 14px', background: 'var(--input-bg)',
    border: '1px solid var(--input-border)', borderRadius: 10,
    color: 'var(--text-primary)', fontSize: 13, outline: 'none',
  },
  selectWrap: { position: 'relative' },
  select: {
    width: '100%', padding: '11px 38px 11px 14px',
    background: 'var(--input-bg)', border: '1px solid var(--input-border)',
    borderRadius: 10, color: 'var(--text-primary)', fontSize: 13,
    outline: 'none', appearance: 'none', cursor: 'pointer',
  },
  chevron: {
    position: 'absolute', right: 12, top: '50%',
    transform: 'translateY(-50%)', pointerEvents: 'none', color: 'var(--text-muted)',
  },
  readonlyField: {
    padding: '11px 14px', background: 'var(--bg-card)',
    border: '1px solid var(--border-color)', borderRadius: 10,
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  },
  readonlyAmt: { fontSize: 18, fontWeight: 800, color: '#00c9a7' },
  readonlyTxt: { fontSize: 13, color: 'var(--text-primary)' },
  readonlyTag: {
    fontSize: 10, fontWeight: 600, padding: '2px 8px', borderRadius: 20,
    background: 'rgba(0,201,167,0.12)', color: '#00c9a7', letterSpacing: 0.3,
  },
  errTxt: { fontSize: 11, color: '#ff4444', marginTop: 2 },
  noPlanBanner: {
    padding: '14px 18px', background: 'rgba(255,180,0,0.08)',
    border: '1px solid rgba(255,180,0,0.25)', borderRadius: 10,
    color: '#f5a623', fontSize: 13,
  },
  primaryBtn: {
    width: '100%', padding: '14px',
    background: 'linear-gradient(135deg, #ff2b2b, #d40000)',
    border: 'none', borderRadius: 12,
    color: '#fff', fontSize: 14, fontWeight: 700,
    cursor: 'pointer', marginTop: 24,
    boxShadow: '0 4px 20px rgba(220,0,0,0.3)',
    transition: 'transform 0.2s, opacity 0.2s',
  },
  ghostBtn: {
    padding: '14px 20px', background: 'var(--bg-card)',
    border: '1px solid var(--border-color)', borderRadius: 12,
    color: 'var(--text-secondary)', fontSize: 13, fontWeight: 600,
    cursor: 'pointer', marginTop: 24,
  },
  summaryStrip: {
    display: 'flex', alignItems: 'center', flexWrap: 'wrap',
    background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    borderRadius: 12, padding: '16px 24px', marginBottom: 28,
  },
  summaryItem: { display: 'flex', flexDirection: 'column', gap: 3, flex: 1, minWidth: 100 },
  summaryLbl: {
    fontSize: 10, color: 'var(--text-muted)',
    textTransform: 'uppercase', letterSpacing: 0.5,
  },
  summaryVal: { fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' },
  summaryDivider: {
    width: 1, height: 36, background: 'var(--border-color)', margin: '0 20px',
  },
  pmGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
    gap: 12, marginBottom: 16,
  },
  pmCard: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
    padding: '18px 12px', borderRadius: 12, border: '2px solid',
    cursor: 'pointer', transition: 'all 0.2s', position: 'relative',
  },
  pmIcon: { fontSize: 24 },
  pmLabel: { fontSize: 13, fontWeight: 600 },
  pmBadge: {
    position: 'absolute', top: 8, right: 8, fontSize: 9, fontWeight: 700,
    padding: '2px 6px', background: 'rgba(220,0,0,0.15)', color: '#e00000',
    borderRadius: 20, letterSpacing: 0.5,
  },
  razorpayNote: {
    padding: '12px 16px', background: 'rgba(220,0,0,0.06)',
    border: '1px solid rgba(220,0,0,0.2)', borderRadius: 10,
    fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6,
    display: 'flex', gap: 8, alignItems: 'flex-start',
  },
  cardNote: {
    padding: '12px 16px', background: 'rgba(0,100,255,0.06)',
    border: '1px solid rgba(0,100,255,0.2)', borderRadius: 10,
    fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6,
  },
  qrNote: {
    padding: '12px 16px', background: 'rgba(0,201,167,0.06)',
    border: '1px solid rgba(0,201,167,0.2)', borderRadius: 10,
    fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6,
    display: 'flex', alignItems: 'center', gap: 8,
  },
  cashNote: {
    padding: '12px 16px', background: 'rgba(245,166,35,0.06)',
    border: '1px solid rgba(245,166,35,0.2)', borderRadius: 10,
    fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6,
  },
  successIcon: { fontSize: 64, marginBottom: 12 },
  successTitle: { fontSize: 22, fontWeight: 700, color: 'var(--text-primary)', margin: '0 0 8px' },
  successSub: { fontSize: 13, color: 'var(--text-muted)', marginBottom: 24 },
  successGrid: {
    background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    borderRadius: 12, overflow: 'hidden', textAlign: 'left',
  },
  successRow: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '12px 20px', borderBottom: '1px solid var(--border-color)',
  },
  successLbl: { fontSize: 12, color: 'var(--text-muted)' },
  successVal: { fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' },
};

// ─── QR Modal styles ───
export const qr: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed', inset: 0,
    background: 'rgba(0,0,0,0.82)',
    backdropFilter: 'blur(10px)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    zIndex: 2000,
    animation: 'qr-fade-in 0.3s ease',
  },
  box: {
    background: 'linear-gradient(180deg, #0f0f0f 0%, #131313 100%)',
    border: '1px solid rgba(0,201,167,0.2)',
    borderRadius: 24,
    width: '100%', maxWidth: 440,
    margin: '0 16px',
    boxShadow: '0 0 0 1px rgba(0,201,167,0.1), 0 40px 100px rgba(0,0,0,0.7)',
    overflow: 'hidden',
    animation: 'qr-fade-in 0.35s cubic-bezier(0.34,1.56,0.64,1)',
  },
  header: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '20px 24px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    background: 'rgba(0,201,167,0.04)',
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 12 },
  gymBadge: {
    width: 38, height: 38,
    background: 'linear-gradient(135deg, #00c9a7, #009977)',
    borderRadius: 10,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    boxShadow: '0 0 20px rgba(0,201,167,0.4)',
    flexShrink: 0,
  },
  gymName: { fontSize: 15, fontWeight: 700, color: '#ffffff', margin: 0 },
  gymSub: { fontSize: 11, color: 'rgba(0,201,167,0.7)', margin: '2px 0 0', letterSpacing: 0.5 },
  closeBtn: {
    background: 'rgba(255,255,255,0.07)', border: 'none',
    color: 'rgba(255,255,255,0.4)', borderRadius: 8,
    width: 30, height: 30, cursor: 'pointer', fontSize: 13,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  amountBanner: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '14px 24px',
    background: 'linear-gradient(90deg, rgba(220,0,0,0.1), rgba(220,0,0,0.04))',
    borderBottom: '1px solid rgba(220,0,0,0.15)',
  },
  amountLabel: {
    fontSize: 12, fontWeight: 600, color: 'rgba(255,255,255,0.5)',
    letterSpacing: 1, textTransform: 'uppercase',
  },
  amountValue: {
    fontSize: 24, fontWeight: 800, color: '#ff2b2b',
    textShadow: '0 0 20px rgba(220,0,0,0.5)',
  },
  detailsStrip: { display: 'flex', borderBottom: '1px solid rgba(255,255,255,0.06)' },
  detailItem: {
    flex: 1, display: 'flex', flexDirection: 'column', gap: 2,
    padding: '12px 16px', borderRight: '1px solid rgba(255,255,255,0.06)',
  },
  detailLabel: {
    fontSize: 9, fontWeight: 600, color: 'rgba(255,255,255,0.35)',
    letterSpacing: 1, textTransform: 'uppercase',
  },
  detailValue: { fontSize: 12, fontWeight: 600, color: '#ffffff' },
  qrSection: {
    padding: '24px 24px 16px',
    display: 'flex', flexDirection: 'column', alignItems: 'center',
  },

  // ── UPDATED: frame fills completely, no gaps ──
  qrFrame: {
    position: 'relative',
    width: 220,
    height: 220,
    borderRadius: 12,
    overflow: 'hidden',
    background: '#ffffff',
    boxShadow: '0 0 0 3px rgba(0,201,167,0.4), 0 0 40px rgba(0,201,167,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  corner: {
    position: 'absolute',
    width: 20, height: 20,
    borderColor: '#00c9a7', borderStyle: 'solid',
    animation: 'corner-pulse 1.8s ease-in-out infinite',
    zIndex: 2,
  },
  cornerTL: { top: 6, left: 6, borderWidth: '2px 0 0 2px', borderRadius: '3px 0 0 0' },
  cornerTR: { top: 6, right: 6, borderWidth: '2px 2px 0 0', borderRadius: '0 3px 0 0' },
  cornerBL: { bottom: 6, left: 6, borderWidth: '0 0 2px 2px', borderRadius: '0 0 0 3px' },
  cornerBR: { bottom: 6, right: 6, borderWidth: '0 2px 2px 0', borderRadius: '0 0 3px 0' },
  scanLine: {
    position: 'absolute', left: 8, right: 8, height: 2,
    background: 'linear-gradient(90deg, transparent, rgba(0,201,167,0.9), transparent)',
    borderRadius: 1, zIndex: 3,
    animation: 'scan-move 2.5s ease-in-out infinite',
    boxShadow: '0 0 8px rgba(0,201,167,0.6)',
  },

  // ── UPDATED: no padding, full cover ──
  qrImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    padding: 0,
  },

  scanHint: { fontSize: 12, color: 'rgba(255,255,255,0.45)', marginTop: 12, marginBottom: 8 },
  upiIcons: { display: 'flex', gap: 8 },
  upiIcon: {
    fontSize: 9, fontWeight: 700, padding: '3px 8px',
    background: 'rgba(255,255,255,0.07)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 20, color: 'rgba(255,255,255,0.45)', letterSpacing: 0.5,
  },
  instructions: {
    display: 'flex', alignItems: 'flex-start', gap: 10,
    margin: '0 24px 16px', padding: '12px 16px',
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.08)', borderRadius: 12,
  },
  instrIcon: { fontSize: 16, flexShrink: 0, marginTop: 1 },
  instrText: { fontSize: 12, color: 'rgba(255,255,255,0.55)', lineHeight: 1.7 },
  checkRow: {
    display: 'flex', alignItems: 'center', gap: 10,
    margin: '0 24px 20px', cursor: 'pointer',
  },
  checkbox: {
    width: 20, height: 20, border: '2px solid', borderRadius: 5,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    transition: 'all 0.2s', flexShrink: 0, cursor: 'pointer',
  },
  checkLabel: {
    fontSize: 12, color: 'rgba(255,255,255,0.5)', lineHeight: 1.5,
    userSelect: 'none',
  },
  actions: { display: 'flex', gap: 10, padding: '0 24px 24px' },
  cancelPayBtn: {
    flex: 1, padding: '13px',
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.1)', borderRadius: 12,
    color: 'rgba(255,255,255,0.5)', fontSize: 13, fontWeight: 600,
    cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7,
  },
  confirmPayBtn: {
    flex: 2, padding: '13px',
    background: 'linear-gradient(135deg, #00c9a7, #009977)',
    border: 'none', borderRadius: 12,
    color: '#ffffff', fontSize: 13, fontWeight: 700,
    cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7,
    boxShadow: '0 4px 20px rgba(0,201,167,0.35)',
  },
  btnSpinner: {
    width: 14, height: 14,
    border: '2px solid rgba(255,255,255,0.3)',
    borderTop: '2px solid #fff', borderRadius: '50%',
    animation: 'spin 0.7s linear infinite', display: 'inline-block',
  },
};

// ─── Card Modal styles ───
export const cm: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)',
    backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center',
    justifyContent: 'center', zIndex: 2000,
  },
  box: {
    background: '#111827', border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 20, width: '100%', maxWidth: 420,
    margin: '0 20px', boxShadow: '0 40px 80px rgba(0,0,0,0.6)', overflow: 'hidden',
  },
  head: {
    display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between',
    padding: '24px 28px 16px',
  },
  title: { fontSize: 18, fontWeight: 700, color: '#fff', margin: 0 },
  sub: { fontSize: 12, color: 'rgba(255,255,255,0.4)', margin: '4px 0 0' },
  closeBtn: {
    background: 'rgba(255,255,255,0.08)', border: 'none',
    color: 'rgba(255,255,255,0.5)', borderRadius: 8,
    width: 30, height: 30, cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13,
  },
  cardOuter: {
    width: 340, height: 200, margin: '0 auto',
    position: 'relative', transformStyle: 'preserve-3d',
    transition: 'transform 0.6s cubic-bezier(0.4,0,0.2,1)',
  },
  cardFront: {
    position: 'absolute', inset: 0,
    background: 'linear-gradient(135deg,#1a2a4a,#0f1e35,#1a3a5c)',
    borderRadius: 16, padding: '24px 28px',
    backfaceVisibility: 'hidden',
    boxShadow: '0 20px 60px rgba(0,0,0,0.5)',
    display: 'flex', flexDirection: 'column', justifyContent: 'space-between',
    border: '1px solid rgba(255,255,255,0.1)',
  },
  cardBack: {
    position: 'absolute', inset: 0,
    background: 'linear-gradient(135deg,#1a2a4a,#0f1e35,#1a3a5c)',
    borderRadius: 16, backfaceVisibility: 'hidden',
    transform: 'rotateY(180deg)',
    boxShadow: '0 20px 60px rgba(0,0,0,0.5)',
    border: '1px solid rgba(255,255,255,0.1)', overflow: 'hidden',
  },
  cardChip: {
    width: 42, height: 32,
    background: 'linear-gradient(135deg,#d4af37,#f5c842)',
    borderRadius: 6, display: 'flex', flexDirection: 'column',
    justifyContent: 'center', gap: 4, padding: '0 8px',
  },
  chipLine: { height: 2, background: 'rgba(0,0,0,0.25)', borderRadius: 1 },
  cardNum: {
    fontSize: 20, fontWeight: 700, color: '#fff',
    letterSpacing: 3, fontFamily: 'monospace', margin: 0,
  },
  cardBottom: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' },
  cardLabel: { fontSize: 9, color: 'rgba(255,255,255,0.5)', letterSpacing: 1, margin: '0 0 3px' },
  cardVal: { fontSize: 13, fontWeight: 600, color: '#fff', margin: 0, letterSpacing: 1 },
  magStripe: { height: 48, background: '#111', marginTop: 28 },
  cvvRow: { display: 'flex', alignItems: 'center', margin: '16px 20px 0', gap: 12 },
  cvvStripe: { flex: 1, height: 36, background: 'rgba(255,255,255,0.9)', borderRadius: 4 },
  cvvVal: {
    fontSize: 18, fontWeight: 700, color: '#fff',
    fontFamily: 'monospace', minWidth: 40, textAlign: 'right',
  },
  cardLabel2: {
    fontSize: 10, color: 'rgba(255,255,255,0.4)',
    letterSpacing: 1, margin: '8px 20px 0', textAlign: 'right',
  },
  fields: { padding: '0 28px 28px', display: 'flex', flexDirection: 'column', gap: 10 },
  fieldWrap: { display: 'flex', flexDirection: 'column', gap: 5 },
  label: { fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.4)', letterSpacing: 0.8 },
  input: {
    padding: '12px 14px', background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.12)', borderRadius: 10,
    color: '#fff', fontSize: 13, outline: 'none',
  },
  inputErr: { borderColor: '#ff4444' },
  err: { fontSize: 11, color: '#ff4444' },
  eyeBtn: {
    position: 'absolute', right: 12, top: '50%',
    transform: 'translateY(-50%)', background: 'none',
    border: 'none', cursor: 'pointer', fontSize: 14, padding: 0,
  },
  totalRow: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '14px 16px', background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.08)', borderRadius: 10, marginTop: 4,
  },
  totalLbl: { fontSize: 13, color: 'rgba(255,255,255,0.6)' },
  totalAmt: { fontSize: 20, fontWeight: 800, color: '#4ade80' },
  payBtn: {
    padding: '15px', marginTop: 4,
    background: 'linear-gradient(135deg,#2563eb,#1d4ed8)',
    border: 'none', borderRadius: 12,
    color: '#fff', fontSize: 15, fontWeight: 700, cursor: 'pointer',
    boxShadow: '0 4px 20px rgba(37,99,235,0.4)', transition: 'opacity 0.2s',
  },
  btnSpinner: {
    width: 16, height: 16, border: '2px solid rgba(255,255,255,0.3)',
    borderTop: '2px solid #fff', borderRadius: '50%',
    animation: 'spin 0.7s linear infinite', display: 'inline-block',
  },
  simNote: {
    fontSize: 11, color: 'rgba(255,255,255,0.25)',
    textAlign: 'center', margin: '4px 0 0',
  },
};