import type { CSSProperties } from 'react';

export const st: Record<string, CSSProperties> = {
  header: {
    height: 72, borderBottom: '1px solid var(--border-color)',
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '0 36px', background: 'var(--bg-secondary)', flexShrink: 0,
  },
  headerTitle: { fontSize: 20, fontWeight: 700, color: 'var(--text-primary)', margin: 0 },
  headerSub: { fontSize: 12, color: 'var(--text-muted)', margin: '2px 0 0' },
  main: { flex: 1, padding: '28px 32px', overflowY: 'auto' },
  statRow: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 16, marginBottom: 24 },
  statCard: {
    background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    borderRadius: 14, padding: '18px 20px',
    display: 'flex', alignItems: 'center', gap: 14,
  },
  statVal: { fontSize: 22, fontWeight: 800, margin: 0 },
  statLbl: { fontSize: 12, color: 'var(--text-muted)', margin: '2px 0 0' },
  bulkResult: {
    background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    borderRadius: 14, padding: '20px 24px', marginBottom: 20,
  },
  bulkResultTitle: { fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', margin: '0 0 14px' },
  bulkResultGrid: { display: 'flex', gap: 32, flexWrap: 'wrap', marginBottom: 16 },
  bulkResultItem: { display: 'flex', flexDirection: 'column', gap: 4 },
  bulkResultVal: { fontSize: 24, fontWeight: 800, color: 'var(--text-primary)' },
  bulkResultLbl: { fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: 0.5 },
  dismissBtn: {
    padding: '7px 18px', background: 'var(--bg-hover)',
    border: '1px solid var(--border-color)', borderRadius: 8,
    color: 'var(--text-secondary)', fontSize: 12, cursor: 'pointer',
  },
  searchFilterRow: { display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 20 },
  searchWrap: { position: 'relative' },
  searchIcon: {
    position: 'absolute', left: 14, top: '50%',
    transform: 'translateY(-50%)', color: 'var(--text-muted)',
  },
  searchInput: {
    width: '100%', padding: '12px 14px 12px 42px',
    background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    borderRadius: 10, color: 'var(--text-primary)', fontSize: 13, outline: 'none',
  },
  filterRow: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  filterBtn: {
    padding: '7px 16px', background: 'var(--bg-card)',
    border: '1px solid var(--border-color)', borderRadius: 20,
    color: 'var(--text-muted)', fontSize: 12, fontWeight: 600,
    cursor: 'pointer', transition: 'all 0.2s',
  },
  filterBtnActive: {
    background: 'rgba(220,0,0,0.12)', border: '1px solid rgba(220,0,0,0.3)', color: '#e00000',
  },
  tableWrap: { overflowX: 'auto', borderRadius: 14, border: '1px solid var(--border-color)' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: {
    padding: '12px 16px', textAlign: 'left', fontSize: 11, fontWeight: 700,
    color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: 0.5,
    background: 'var(--bg-card)', borderBottom: '1px solid var(--border-color)',
    whiteSpace: 'nowrap',
  },
  tr: { borderBottom: '1px solid var(--border-color)', transition: 'background 0.15s' },
  td: { padding: '14px 16px', color: 'var(--text-primary)', whiteSpace: 'nowrap', verticalAlign: 'middle' },
  memberIdBadge: {
    fontSize: 11, fontWeight: 700, padding: '3px 8px',
    background: 'rgba(220,0,0,0.1)', color: '#e00000', borderRadius: 6, letterSpacing: 0.5,
  },
  nameCell: { display: 'flex', alignItems: 'center', gap: 10 },
  avatar: {
    width: 32, height: 32, borderRadius: '50%',
    color: '#fff', fontSize: 13, fontWeight: 700,
    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  nameTxt: { fontSize: 13, fontWeight: 600, color: 'var(--text-primary)', margin: 0 },
  emailTxt: { fontSize: 11, color: 'var(--text-muted)', margin: '2px 0 0' },
  phoneTxt: { fontSize: 13, color: 'var(--text-secondary)' },
  planBadge: {
    fontSize: 11, fontWeight: 600, padding: '3px 8px',
    background: 'rgba(220,0,0,0.08)', color: '#e00000', borderRadius: 6,
  },
  durationTxt: { fontSize: 12, color: 'var(--text-secondary)' },
  amtTxt: { fontSize: 13, fontWeight: 700, color: 'var(--text-secondary)' },
  dateTxt: { fontSize: 12, color: 'var(--text-primary)' },
  daysBadge: { fontSize: 11, fontWeight: 600, padding: '4px 10px', borderRadius: 20 },
  expiredBadge: { fontSize: 11, fontWeight: 600, color: '#e00000' },
  emailBtn: {
    width: 32, height: 32, borderRadius: 8, border: 'none',
    background: 'rgba(0,100,255,0.1)', color: '#4d94ff',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer', flexShrink: 0,
  },
  waBtn: {
    width: 32, height: 32, borderRadius: 8, border: 'none',
    background: 'rgba(37,211,102,0.12)', color: '#25d366',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer', flexShrink: 0,
  },
  bulkBtn: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '10px 18px', background: 'linear-gradient(135deg, #ff2b2b, #d40000)',
    border: 'none', borderRadius: 12, color: '#fff', fontSize: 13, fontWeight: 600,
    cursor: 'pointer', boxShadow: '0 4px 16px rgba(220,0,0,0.3)', transition: 'opacity 0.2s',
  },
  btnSpinner: {
    width: 14, height: 14, border: '2px solid rgba(255,255,255,0.3)',
    borderTop: '2px solid #fff', borderRadius: '50%',
    animation: 'spin 0.7s linear infinite', display: 'inline-block',
  },
  btnSpinnerSm: {
    width: 12, height: 12, border: '2px solid rgba(77,148,255,0.3)',
    borderTop: '2px solid #4d94ff', borderRadius: '50%',
    animation: 'spin 0.7s linear infinite',
  },
  centerMsg: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingTop: 80, gap: 12 },
  spinner: {
    width: 36, height: 36, border: '3px solid var(--border-color)',
    borderTop: '3px solid #e00000', borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  emptyTxt: { fontSize: 15, color: 'var(--text-muted)', margin: 0 },
  toastContainer: {
    position: 'fixed', top: 20, right: 20,
    display: 'flex', flexDirection: 'column', gap: 10, zIndex: 9999,
  },
  toast: {
    padding: '12px 20px', borderRadius: 12,
    color: '#fff', fontSize: 13, fontWeight: 600,
    boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
    animation: 'fadeUp 0.3s ease',
  },
};