import type { CSSProperties } from 'react';

export const s: Record<string, CSSProperties> = {
  header: {
    height: 72, borderBottom: '1px solid var(--border-color)',
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '0 36px', background: 'var(--bg-secondary)', flexShrink: 0,
  },
  headerTitle: { fontSize: 20, fontWeight: 700, color: 'var(--text-primary)', margin: 0 },
  headerSub:   { fontSize: 12, color: 'var(--text-muted)', margin: '2px 0 0' },
  main:        { flex: 1, padding: '28px 32px', overflowY: 'auto' },
  statRow: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 14, marginBottom: 24 },
  statCard: {
    background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    borderRadius: 12, padding: '16px 18px',
    display: 'flex', alignItems: 'center', gap: 12,
  },
  statVal: { fontSize: 20, fontWeight: 800, margin: 0 },
  statLbl: { fontSize: 11, color: 'var(--text-muted)', margin: '2px 0 0' },
  toolbarRow: { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 12, marginBottom: 18 },
  searchWrap:  { position: 'relative', flex: 1, minWidth: 240 },
  searchIcon:  { position: 'absolute', left: 13, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' },
  searchInput: {
    width: '100%', padding: '11px 36px 11px 40px',
    background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    borderRadius: 10, color: 'var(--text-primary)', fontSize: 13, outline: 'none',
  },
  clearBtn: {
    position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)',
    background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: 13,
  },
  filterGroup: { display: 'flex', gap: 8 },
  filterBtn: {
    padding: '8px 16px', borderRadius: 20, border: '1px solid var(--border-color)',
    background: 'var(--bg-card)', color: 'var(--text-muted)',
    fontSize: 12, fontWeight: 600, cursor: 'pointer', transition: 'all 0.2s',
  },
  filterBtnActive: { borderColor: '#845ef7', color: '#845ef7', background: 'rgba(132,94,247,0.08)' },
  pageSizeWrap:   { display: 'flex', alignItems: 'center', gap: 8 },
  pageSizeLbl:    { fontSize: 12, color: 'var(--text-muted)' },
  pageSizeSelect: {
    padding: '7px 10px', background: 'var(--bg-card)',
    border: '1px solid var(--border-color)', borderRadius: 8,
    color: 'var(--text-primary)', fontSize: 12, outline: 'none', cursor: 'pointer',
  },
  tableWrap: { overflowX: 'auto', borderRadius: 14, border: '1px solid var(--border-color)', marginBottom: 20 },
  table:     { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: {
    padding: '12px 14px', textAlign: 'left', fontSize: 10, fontWeight: 700,
    color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: 0.5,
    background: 'var(--bg-card)', borderBottom: '1px solid var(--border-color)',
    whiteSpace: 'nowrap',
  },
  tr:        { borderBottom: '1px solid var(--border-color)', transition: 'background 0.12s' },
  trExpired: { background: 'rgba(220,0,0,0.02)' },
  td:        { padding: '13px 14px', whiteSpace: 'nowrap', verticalAlign: 'middle' },
  memberIdBadge: { fontSize: 10, fontWeight: 700, padding: '3px 7px', borderRadius: 5, letterSpacing: 0.5 },
  nameCell:      { display: 'flex', alignItems: 'center', gap: 9 },
  avatar: {
    width: 30, height: 30, borderRadius: '50%',
    color: '#fff', fontSize: 12, fontWeight: 700,
    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  nameTxt:  { fontSize: 13, fontWeight: 600, margin: 0 },
  subTxt:   { fontSize: 10, color: 'var(--text-muted)', margin: '1px 0 0' },
  cellTxt:  { fontSize: 12 },
  planBadge:   { fontSize: 10, fontWeight: 600, padding: '3px 7px', borderRadius: 5 },
  statusBadge: { fontSize: 10, fontWeight: 700, padding: '3px 8px', borderRadius: 20 },
  viewBtn: {
    width: 28, height: 28, borderRadius: 7, border: 'none',
    background: 'rgba(132,94,247,0.1)', color: '#845ef7',
    display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
  },
  editBtn: {
    width: 28, height: 28, borderRadius: 7, border: 'none',
    background: 'rgba(0,201,167,0.1)', color: '#00c9a7',
    display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
  },
  delBtn: {
    width: 28, height: 28, borderRadius: 7, border: 'none',
    background: 'rgba(220,0,0,0.08)', color: '#ff4444',
    display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
  },
  paginationRow:  { display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 },
  paginationInfo: { fontSize: 12, color: 'var(--text-muted)' },
  pageButtons:    { display: 'flex', gap: 6, alignItems: 'center', flexWrap: 'wrap' },
  pageBtn: {
    padding: '7px 12px', borderRadius: 8, border: '1px solid var(--border-color)',
    background: 'var(--bg-card)', color: 'var(--text-secondary)',
    fontSize: 12, fontWeight: 600, cursor: 'pointer', transition: 'all 0.15s',
  },
  pageBtnActive: {
    background: '#e00000', borderColor: '#e00000',
    color: '#fff', boxShadow: '0 2px 8px rgba(220,0,0,0.3)',
  },
  pageDots: { fontSize: 13, color: 'var(--text-muted)', padding: '0 4px' },
  centerMsg: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingTop: 80, gap: 12 },
  spinner: {
    width: 34, height: 34, border: '3px solid var(--border-color)',
    borderTop: '3px solid #e00000', borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  loadTxt:  { fontSize: 13, color: 'var(--text-muted)', margin: 0 },
  emptyTxt: { fontSize: 14, color: 'var(--text-muted)', margin: 0 },
};

export const md: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.65)',
    backdropFilter: 'blur(6px)', display: 'flex', alignItems: 'center',
    justifyContent: 'center', zIndex: 1000,
  },
  box: {
    background: 'var(--bg-secondary)', border: '1px solid var(--border-color)',
    borderRadius: 20, width: '100%', maxWidth: 520,
    margin: '0 20px', boxShadow: '0 40px 80px rgba(0,0,0,0.5)', overflow: 'hidden',
  },
  head: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '22px 28px',
  },
  avatar: {
    width: 44, height: 44, borderRadius: '50%',
    color: '#fff', fontSize: 18, fontWeight: 700,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  title:       { fontSize: 16, fontWeight: 700, color: 'var(--text-primary)', margin: '0 0 4px' },
  statusBadge: { fontSize: 11, fontWeight: 700, padding: '3px 10px', borderRadius: 20 },
  closeBtn: {
    background: 'rgba(255,255,255,0.07)', border: 'none',
    color: 'var(--text-muted)', borderRadius: 8,
    width: 30, height: 30, cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 13, flexShrink: 0,
  },
  body: { padding: '20px 28px' },
  grid: {
    display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 0,
    border: '1px solid var(--border-color)', borderRadius: 12, overflow: 'hidden',
  },
  detailRow: {
    display: 'flex', flexDirection: 'column', gap: 3,
    padding: '12px 16px', borderBottom: '1px solid var(--border-color)',
    borderRight: '1px solid var(--border-color)',
  },
  detailLbl: { fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: 0.5 },
  detailVal: { fontSize: 13, color: 'var(--text-primary)', fontWeight: 600 },
  field:     { display: 'flex', flexDirection: 'column', gap: 5 },
  label:     { fontSize: 11, fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: 0.5 },
  input: {
    padding: '10px 13px', background: 'var(--input-bg)',
    border: '1px solid var(--input-border)', borderRadius: 9,
    color: 'var(--text-primary)', fontSize: 13, outline: 'none',
  },
  footer:    { padding: '16px 28px 24px', display: 'flex', justifyContent: 'flex-end' },
  editBtn: {
    padding: '10px 22px', background: 'linear-gradient(135deg, #00c9a7, #009977)',
    border: 'none', borderRadius: 10, color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
  },
  cancelBtn: {
    flex: 1, padding: '11px', background: 'var(--bg-card)',
    border: '1px solid var(--border-color)', borderRadius: 10,
    color: 'var(--text-secondary)', fontSize: 13, fontWeight: 600, cursor: 'pointer',
  },
  saveBtn: {
    flex: 1, padding: '11px', background: 'linear-gradient(135deg, #00c9a7, #009977)',
    border: 'none', borderRadius: 10, color: '#fff', fontSize: 13, fontWeight: 700, cursor: 'pointer',
  },
};